### ISSUE TITLE
Potentially unexpected behaviour with "=" character

### ISSUE THREAD

**Issue by s16h** [r1chardj0n3s/parse#106]
Is it expected that `parse("b={}", "ab=cd")` is `None`? I was expecting to get `<Result ('cd',) {}>`.

**Comment by vladikcomper** [comment]
Did you mean `parse("ab={}", "ab=cd")`? Because your expression and the string do not actually match.
If you're trying to match any characters at the beginning of the string, before the `...b=` part, you might be looking for something like this:
```
>>> parse("{}b={}", "ab=cd")
<Result ('a', 'cd') {}>
```

**Comment by r1chardj0n3s** [comment]
Or you could use search to find your parse pattern inside a larger string. Either way, looks like this report may be closed.

**Comment by s16h** [comment]
Thanks for the clarification. I has misunderstood.
