### ISSUE TITLE
[wishlist] Ability to get a set of values in a result

### ISSUE THREAD

**Issue by victorromeo** [r1chardj0n3s/parse#108]
As an extension to #13 can I request inbuilt support for returning a collection of 'n' elements?

When I'm parsing the output of `sudo iwlist wlan0 scan` I get variable length responses, which require additional plumbing.

```
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 18 Mb/s
                              24 Mb/s; 36 Mb/s; 54 Mb/s
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 48 Mb/s
...
                        Pairwise Ciphers (2) : TKIP CCMP
and
                        Pairwise Ciphers (1) : CCMP
```

I know this is special case, but lists of values in strings are not unusual.  May I get a wishlist item?

**Comment by jenisys** [comment]
[parse_type](https://github.com/jenisys/parse_type) allows to specify a type that contains 0..N or 1..N items.
This type can then be used/registered in a parse parser.

SEE:
* https://github.com/jenisys/parse_type#cardinality

**Comment by victorromeo** [comment]
Thanks!
