### ISSUE TITLE
seach cut the result with {:^}

### ISSUE THREAD

**Issue by diegomcas** [r1chardj0n3s/parse#112]
from parse impor *
str = '     12  ,      34   '

# Incorrect with search
print(search('{:^},{:^}', a))
<Result ('12', '3') {}>

# Correct with parse
print(parse('{:^},{:^}', a))
<Result ('12', '34') {}>

**Comment by r1chardj0n3s** [comment]
Thanks, I've altered the code to have it attempt to match more of the trailing centered content.
