### ISSUE TITLE
add dot access interface to `result` object

### ISSUE THREAD

**Issue by CircleOnCircles** [r1chardj0n3s/parse#117]
I would like to know what author opinion about dot access to named field.
e.g.
```python
r = parse("Bring out the holy {item}", "Bring out the holy hand grenade")
print(r.item) # 'hand grenade'
```

**Comment by r1chardj0n3s** [comment]
I'm not a fan of this, sorry. There should be one obvious way to do it.

**Comment by CircleOnCircles** [comment]
Respected that, the zen.

but,  you know this is common and cool. For example,
`pandas` allow dataframe to be accessed like this.
`df['ColumnA']` as well as `df.ColumnA`.

**Comment by CircleOnCircles** [comment]
I created a fork for this at https://github.com/CircleOnCircles/parse.
