### ISSUE TITLE
Suggestion :u to detect url

### ISSUE THREAD

**Issue by ukgenes** [r1chardj0n3s/parse#141]
{:u} to detect http[s}://kjjhh.com/asdhfk/sdfh/adsf?dsf=jkk

Great library!!!

**Comment by jenisys** [comment]
Wouldn't it be better to provide a readable name, like "{:Url}" or "{:url} instead of "{:u}" ?!?

NOTE THAT:
You can already use that by registering your own type.
You just need to figure out what the regex pattern should look like.
