### ISSUE TITLE
pip install parse doesn't work

### ISSUE THREAD

**Issue by superhiro2a** [r1chardj0n3s/parse#143]
I run in cmd pip install parse, but doesnt  work.

Requirement already satisfied: parse in c:\users\mynamecom\appdata\local\programs\python\python310\lib\site-packages (1.19.0)

but

in running in cmd script python 

    from parse import parse
ModuleNotFoundError: No module named 'parse'

**Comment by jenisys** [comment]
Mmh, works for me with Python 3.10 and parse v1.19.0 (but I am not using Windows).
I assume the problem is somewhere on your side.
For example, you are using another python version that is not using your `site-packages` directory that you mentioned above.

To better diagnose and understand it, do the following:

```python
# ORIGINAL: from parse import parse
# HINT: May need to fix the double-quotes style forced by the Github editor.
from __future__ import print_function
import sys

try:
    from parse import parse
except ImportError as e:
    print(„EXCEPTION %s: %s“ % (e.__class__.__name__, e))
    print(„PYTHON.version: %s“ % sys.version)
    for p in sys.path:
        print(p)
```

WORST CASE RESOLUTION:

```
python3 -mpip install -U parse
# OR:
C:\path_to_your\python_version\python.exe -mpip install -U parse
```

**Comment by Irtiza90** [comment]
You might be installing packages to another version of python or you're running the code with a different version
On windows you should use the `py` launcher

first run `py -0` to see which versions of python you have in your system

then to specify a python version you can do `py -3.10`, and then
```bash
# to install the package
&> py -3.10  -m pip install parse

# to run the file
&> py -3.10 filename.py
```

**Comment by wimglenn** [comment]
Not reproducible.
