### ISSUE TITLE
Possible to publish wheel?

### ISSUE THREAD

**Issue by mneil** [r1chardj0n3s/parse#144]
Would it be possible for you to publish a whl for this package? I could attempt to enumerate benefits and reasons why but, honestly, it's a bit of a selfish request :).

I recently started contributing to [pyodide](https://github.com/pyodide/pyodide) which is compiling python to WASM. Pyodide contains its own implementation of pip called micropip. One of the limitations of micropip is that is only supports .whl distributions. Parse is used as a transient dependency of many other tools. Specifically pylint and behave use parse at some point. This means neither of these packages are capable of running in pyodide.

**Comment by mbilalshaikh** [comment]
Need whl for running this with Azure Automations. parse is in dependency to a lot of other packages, therefore .whl is a must for its use case for Azure automations related to scraping.
