### ISSUE TITLE
Move to `pyproject.toml` instead of `setup.py` for packaging

### ISSUE THREAD

**Issue by gahjelle** [r1chardj0n3s/parse#147]
When installing `parse` with a recent version of Pip, I get the following warning:

```
DEPRECATION: parse is being installed using the legacy 'setup.py install' method, because it
does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce
this behaviour change. A possible replacement is to enable the '--use-pep517' option.
Discussion can be found at https://github.com/pypa/pip/issues/8559
```

@r1chardj0n3s Would you be interested in a PR moving to a "modern" build system? I can also update the tests and classifiers so that they run on the currently supported Python versions: 3.7 to 3.11

**Comment by rnickle** [comment]
Running into a 517 issue with pip 23.0.1, poetry 1.2.2 and python 3.10:

```text
Note: This error originates from the build backend, and is likely not a problem with poetry but with parse (1.19.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "parse (==1.19.0)"'.
```
On the other hand, I seem to have no trouble at all building _parse_ as suggested:

```text
pip wheel --use-pep517 "parse (==1.19.0)" --no-cache-dir
```

**Comment by wimglenn** [comment]
This is also because it's installing from sdist (no wheel on PyPI).
Related: https://github.com/r1chardj0n3s/parse/issues/144

**Comment by wildone** [comment]
Addin

> Running into a 517 issue with pip 23.0.1, poetry 1.2.2 and python 3.10:
> 
> ```
> Note: This error originates from the build backend, and is likely not a problem with poetry but with parse (1.19.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "parse (==1.19.0)"'.
> ```
> 
> On the other hand, I seem to have no trouble at all building _parse_ as suggested:
> 
> ```
> pip wheel --use-pep517 "parse (==1.19.0)" --no-cache-dir
> ```

Adding `--use-pep517 "parse (==1.19.0)"` to my pip install command worked! Thank you. I am on Python 3.10.
