### ISSUE TITLE
Hash mismatch when fetching 1.19.0

### ISSUE THREAD

**Issue by danielhoherd** [r1chardj0n3s/parse#158]
I have observed this error in one of our CI pipelines:

```
Collecting parse==1.19.0
  Downloading parse-1.19.0-py2.py3-none-any.whl (18 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    parse==1.19.0 from https://files.pythonhosted.org/packages/41/d4/ba354b3ee3c38a4fb0d4a95e66c565e75a3924c57a558648ad0b905510d5/parse-1.19.0-py2.py3-none-any.whl (from -r /home/circleci/project/requirements/component_test.txt (line 208)):
        Expected sha256 9ff82852bcb65d139813e2a5197627a94966245c897796760a3a2a8eb66f020b
             Got        6ce007645384a91150cb7cd7c8a9db2559e273c2e2542b508cd1e342508c2601
```

This hash was resolved by pip-tools `pip-compile` on 2022-07-01 and has been working fine between then and and 2023-06-15. Unfortunately the repo where this was discovered is private so I can't link it here, but this is the relevant part from requirements.txt which was committed on 2022-07-01:
```
parse==1.19.0 \
    --hash=sha256:9ff82852bcb65d139813e2a5197627a94966245c897796760a3a2a8eb66f020b
```

The last CI job we ran where the hash mismatch did not occur was 2023-06-15.

The first time the hash mismatch occurred was on 2023-06-17.

**Comment by uranusjr** [comment]
I hand-downloaded and checked, the artifact on PyPI matches the hash. This may be a network issue in the CI environment that corrupts the download.

**Comment by wimglenn** [comment]
It's either a bug in pip or a bug in pipenv.
9ff82852bcb65d139813e2a5197627a94966245c897796760a3a2a8eb66f020b is the correct sha256 for parse-1.19.0.tar.gz
6ce007645384a91150cb7cd7c8a9db2559e273c2e2542b508cd1e342508c2601 is the correct sha256 for parse-1.19.0-py2.py3-none-any.whl
The tooling should not be comparing the hash of an sdist with the hash of a wheel.

Related: https://github.com/pypa/pipenv/issues/3893

**Comment by wimglenn** [comment]
Closing because there's nothing actionable for parse here.
