### ISSUE TITLE
Bug in {:ta} and {:tg} parsing for AM/PM

### ISSUE THREAD

**Issue by donovandak** [r1chardj0n3s/parse#16]
When using the :ta parsing format, the hour between Noon and 13:00 (aka 1:00PM) generates a ValueError in datetime because hour must be in the range 0..23.  

Example:

> > > parse.**version**
> > > '1.6.2'
> > > 
> > > parse.parse('Meet at {:tg}', 'Meet at 1/2/2011 1:00 PM')
> > > <Result (datetime.datetime(2011, 2, 1, 13, 0),) {}>

example from the documentation.  Now, changing this to 12:45 pm doesn't work.

> > > parse.parse('Meet at {:tg}', 'Meet at 1/2/2011 12:45 PM')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "//anaconda/lib/python2.7/site-packages/parse-1.6.2-py2.7.egg/parse.py", line 983, in parse
> > >     return Parser(format, extra_types=extra_types).parse(string)
> > >   File "//anaconda/lib/python2.7/site-packages/parse-1.6.2-py2.7.egg/parse.py", line 640, in parse
> > >     return self._generate_result(m)
> > >   File "//anaconda/lib/python2.7/site-packages/parse-1.6.2-py2.7.egg/parse.py", line 678, in _generate_result
> > >     fixed_fields[n] = self._type_conversions[n](fixed_fields[n], m)
> > >   File "//anaconda/lib/python2.7/site-packages/parse-1.6.2-py2.7.egg/parse.py", line 518, in date_convert
> > >     d = datetime(y, m, d, H, M, S, u, tzinfo=tz)
> > > ValueError: hour must be in 0..23

**Comment by r1chardj0n3s** [comment]
The fix for this issue was bogus, and has been corrected in addressing issue #57
