### ISSUE TITLE
Usage with pandas df.str.extract and .match?

### ISSUE THREAD

**Issue by marfel** [r1chardj0n3s/parse#177]
I have several large DataFrames I need to apply regex to. From what I understand, `parse` uses compiled regexes internally, therefore it should be possible to use them with `pandas`. But when writing something like

```python
extracted = df.mycolumn.str.extract(parse.compile(my_regex))
``` 

`pandas` throws

```
TypeError: first argument must be string or compiled pattern
```

Is the `re.Pattern` in the `parser.Parser` object accessible from the outside somewhere?

**Comment by wimglenn** [comment]
The argument to `parse.compile` is not a regex. It's a format string. The internal regexen used by parse are not publicly accessible, but take a look at a parser's `_search_re` and `_match_re` attributes to see how the sausage is made.
