### ISSUE TITLE
Cardinality support

### ISSUE THREAD

**Issue by fliiiix** [r1chardj0n3s/parse#181]
For [radish](https://github.com/radish-bdd/radish) we wrongly documented that it is possible to combine the standard types from parse with a cardinality

> These standard types can be combined with the following cardinalities:
> "{numbers:d}"     #< Cardinality: 1    (one; the normal case)
> "{number:d?}"     #< Cardinality: 0..1 (zero or one  = optional)
> "{numbers:d*}"    #< Cardinality: 0..* (zero or more = many0)
> "{numbers:d+}"    #< Cardinality: 1..* (one  or more = many)

Which might have worked somehow or maybe according to my digging was wrong since the start.
https://github.com/radish-bdd/radish/issues/130

Now `parse` itself does obviously not support any cardinality functions but `parse_type` from @jenisys does.
But it seems that `parse_type` is not able to add cardinality to the default types because of the design of `parse`

> The information for the built-in types in the parse module are deeply embedded in the implementation and not easily accessible.
https://github.com/jenisys/parse_type/issues/9#issuecomment-331716708

My question would be if there is any interest in making the built-in types more accessible in a way `parse_type` could consume?

**Comment by wimglenn** [comment]
Well, since there is an easy workaround (stick to [user-defined types](https://github.com/jenisys/parse_type/issues/10#issuecomment-1774114248)) and there has not been much interest since those 2017 issues... If someone can do it in a clean and tested way I'm not against the idea, but I'm not too interested in working on this myself.

**Comment by fliiiix** [comment]
Perfect i linked this issue from radish documentation, if someone wants support for that they should contribute that :D I assume there are a few users a year which would like to use that but as it is simpler for everyone to work around it i assume that's what most of them do 

if i find time i will give it a try but this also has very low prio for me personally
