### ISSUE TITLE
How to get the desired result？

### ISSUE THREAD

**Issue by gitlGl** [r1chardj0n3s/parse#186]
![mmexport1724149280752.png](https://github.com/user-attachments/assets/e3d17483-adc6-402b-806f-56fdac017fc6)

**Comment by jenisys** [comment]
* Use `format_ = „{part1}_2017_{part2}_{part3}xxx.txt“` (xxx mean your Chinese letters in your original format string)
* Use typed-parameters in format, like: `format_ = „{part1:d}_2017_{part2:d}_{part3:d}xxx.txt“`

**Comment by gitlGl** [comment]
sorry,I made a mistake. Thank you for your help.
That's what I actually want .
![mmexport1724152754597.png](https://github.com/user-attachments/assets/c668677c-ae44-4f02-a9c8-ec798874a7da)

**Comment by gitlGl** [comment]
> * Use `format_ = „{part1}_2017_{part2}_{part3}xxx.txt“` (xxx mean your Chinese letters in your original format string)
> * Use typed-parameters in format, like: `format_ = „{part1:d}_2017_{part2:d}_{part3:d}xxx.txt“`

sorry,I made a mistake. Thank you for your help.
That's what I actually want .

![mmexport1724152754597.png](https://github.com/user-attachments/assets/866d19ab-cdca-47e4-a7fb-169d8e460269)

**Comment by gitlGl** [comment]
sorry,I made a mistake. Thank you for your help.
That's what I actually want .
![mmexport1724152754597.png](https://github.com/user-attachments/assets/c668677c-ae44-4f02-a9c8-ec798874a7da)

  want 
part1 000728
part2 2016

**Comment by gitlGl** [comment]
> > * Use `format_ = „{part1}_2017_{part2}_{part3}xxx.txt“` (xxx mean your Chinese letters in your original format string)
> > * Use typed-parameters in format, like: `format_ = „{part1:d}_2017_{part2:d}_{part3:d}xxx.txt“`
> 
> sorry,I made a mistake. Thank you for your help.
> That's what I actually want .
> 
> ![mmexport1724152754597.png](https://github.com/user-attachments/assets/866d19ab-cdca-47e4-a7fb-169d8e460269)
> 
> 

want
part1 000728
part2 2016

**Comment by gitlGl** [comment]
sorry,I made a mistake. Thank you for your help.
That's what I actually want .
![mmexport1724152754597.png](https://github.com/user-attachments/assets/c668677c-ae44-4f02-a9c8-ec798874a7da)

  want 
part1 000728
part2 2016
    i got it
