### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by jarek** [r1chardj0n3s/parse#29]
Ctrl+F "unicode" on README.rst here and on https://pypi.python.org/pypi/parse doesn't find anything. parse appears to hang indefinitely on unicode strings (as with e.g. `from __future__ import unicode_literals`). Is that the case? Is there any expectation it'll work in the future?

**Comment by r1chardj0n3s** [comment]
I wrote a simple test and cannot reproduce this issue (it passes):

```
    def test_unicode(self):
        # issue29: make sure unicode is parseable
        r = parse.parse('{}', u't€ststr')
        self.assertEqual(r[0], u't€ststr')
```
