### ISSUE TITLE
Result.__contains__ not implemented

### ISSUE THREAD

**Issue by jayvdb** [r1chardj0n3s/parse#31]
`Result.__getitem__` is implemented to perform lookup using index or key, but `Result` doesnt implement `__contains__` and doesnt inherit from `abc.Mapping`

As a result, the following fails:

``` python
    if 'foo' in result:
         blah['foo'] = result['foo']
```

instead the following needs to be used:

``` python
    try:
         blah['foo'] = result['foo']
    except KeyError:
        pass
```

**Comment by r1chardj0n3s** [comment]
I don't believe it's possible for this class to implement abc.Mapping given the way in which __getitem__ maps to both a list and a dictionary. Even adding __contains__ has me concerned: should it check in *both* the named result keys (mapping contains behaviour) *and* the fixed result items (list contains behaviour)?
