### ISSUE TITLE
Lookup pattern but do not generate results

### ISSUE THREAD

**Issue by timofurrer** [r1chardj0n3s/parse#37]
Is there a way to search for a string but not generate the results?

This would be especially useful when I have custom type converters but want to evaluate those later. I just want to make search my string is valid.

**Comment by timofurrer** [comment]
See #38

**Comment by jenisys** [comment]
@timofurrer 
Maybe you looking for something, like: 
* ``(?:...)``       Non-capturing version of regular parens
* ``(?=...)``      Lookahead assertion, match without consuming

SEE ALSO:
* [tartley/python-regex-cheatsheet](https://github.com/tartley/python-regex-cheatsheet/blob/master/cheatsheet.rst)
* https://doughellmann.com/presentations/regexes-fear/#/43
* https://pymotw.com/3/re/index.html (see: re_groups_noncapturing.py)

**Comment by timofurrer** [comment]
No, I don't. I just want `parse.search` to **not** run the actual custom type converter function.

**Comment by timofurrer** [comment]
The proposed feature was merged. See #38 :tada:
