### ISSUE TITLE
Curious: why wasn't stdlib `string.Formatter().parse` used

### ISSUE THREAD

**Issue by asottile** [r1chardj0n3s/parse#39]
Mostly just curious, not an actual bug.

I'm working on a (tangentially) related idea of mine to rewrite format strings.

https://docs.python.org/3/library/string.html#string.Formatter.parse

**Comment by r1chardj0n3s** [comment]
Didn't know about it! Simple as that :-)

**Comment by asottile** [comment]
Awesome, was worried there were hidden spiders :D

**Comment by timofurrer** [comment]
@asottile In addition `parse` allows you to specify custom type converters which [Formatter.parse](https://docs.python.org/3/library/string.html#string.Formatter.parse) doesn't

**Comment by asottile** [comment]
`Formatter#parse` seems to support custom type converters as well:

```python
>>> list(Formatter().parse('{0!t}'))
[('', '0', '', 't')]
>>> list(Formatter().parse('{0!y}'))
[('', '0', '', 'y')]
>>> list(Formatter().parse('hello {0!q}'))
[('hello ', '0', '', 'q')]
```

`Formatter#parse` however doesn't replace the functionality of this library, it simply might've made parsing the actual format strings easier.
