### ISSUE TITLE
possible to specify "hungry" format specs? 

### ISSUE THREAD

**Issue by Ricyteach** [r1chardj0n3s/parse#48]
I think this is more of a question, but it may be an issue as well. 

If I format the following format spec string with `values`: 

    fmat='{}{}'
    values=['a','b']

I of course get this result: 

    >>> fmat.format(*values)
    'ab'

And `parse` handles this as expected. 

    >>> list(parse(fmat,'ab'))
    ['a', 'b']

However, I could get the same result by supplying these arguments (the final arg just being an empty string): 

    >>> values=['ab','']
    >>> fmat.format(*values)
    'ab'

The default `parse` behavior becomes a bit more clear when I do this: 

    >>> list(parse('{}{}', 'abcdef'))
    ['a', 'bcdef']

So it seems that the format fields "eat" as little as possible. This definitely makes sense as a default behavior. 

If I naively supply the optional third argument to `parse`, in an attempt to signal that a field should be as hungry as possible and "eat" any string (`str`) that it finds (if it can), I get the same result: 

    >>> list(parse('{:s}{:s}', 'abcdef', dict(s=str))
    ['a', 'bcdef'] # rather than ['abcdef', '']

Any ideas on how to get the last argument to be the empty string using the existing API? 

I do understand that an option like this would be tough to implement. For example: how should this be handled? 

    >>> list(parse('{:s}{:s}{:s}{:d}{:d}', 'abc123', dict(s=str), hungry=True))

Should it return `None`, e.g.?:

    ['abc123','','', ERROR, ERROR] # errors because no integers to eat after first string eats everything

Or should it pick out the integers first and leave the leftovers for the other fields (i.e., integers are hungrier than strings)? 

    ['abc','','', 12, 3]

(NOTE in the last example the integers  would also be "hungry", but not hungry enough to cause an error; i.e., integers are hungrier than strings, but not more hungry than each other.)

**Comment by Ricyteach** [comment]
I have subsequently noticed this unexpected behavior: 

    >>> parse('{}{:d}', 'abcd1')
    <Result ('a', 1) {}>

However: 

    >>> parse('{}{:d}', 'abcdefg1')
    <Result ('abcdefg', 1) {}>

This looks like a bug to me. Could be wrong.

**Comment by r1chardj0n3s** [comment]
The ambiguity you mention - there being many ways to potentially match the format spec to the string - means I believe the only solution is to allow coding of width expectations in the parse string (just like format strings). This is captured in issue #40.
