### ISSUE TITLE
Problem with findall in parse module

### ISSUE THREAD

**Issue by Sumant-Mahadik** [r1chardj0n3s/parse#54]
Reference link : https://pypi.python.org/pypi/parse

data = """ 0 2 PRLI Def 666E00 B A 0 0
1 2 PRLI Def 017000 B A 0 0"""

for x in parse.findall("{Id:^d} {Index:^d} {State:^} {Emulation:^} {ID:^} {NN:^} {PN:^} {ABTS:^d} {SRR:^d}\n", data):
print ("====", x.named)

Above code will and and gets hang(stuck) after printing first line.
But if we reduce number of columns then it will work fine.
also if there is difference in number of columns in data and pattern string then findall will hang.

**Comment by r1chardj0n3s** [comment]
I don't see that failure using Python 3.5 on Linux. What version of Python on what OS are you using?

**Comment by r1chardj0n3s** [comment]
Closing this in the absence of additional information.
