### ISSUE TITLE
PM handling

### ISSUE THREAD

**Issue by MPagel** [r1chardj0n3s/parse#57]
> the AM/PM are optional, and if PM is found then 12 hours will be added to the datetime object's hours amount - even if the hour is greater than 12 (for consistency.)

I realize you've already chosen your poison here, but the "add 12 always" rule either needs an explicit exception, or it should just do away with the "add 12 to PM values."  Why?

noon is 12:00PM.  15 minutes after noon is 12:15PM. 12 should NOT be added to these value, or they'll register as later than e.g. 9:24PM.

In fact, 12AM (and 12:15AM) should result in a SUBTRACTION of 12 hours, as it occurs prior to 1AM on the given day.

Both issues can be worked around by assuming in the presence of AM/PM indicators, a subtraction of 12 is done. So, the later adding of 12 hours for having "PM" would restore the timeline.

Silly ancient peoples not inventing the concept of "0". Silly us for continuing to stick with a counter-intuitive notation.

**Comment by r1chardj0n3s** [comment]
I apologise for my tardiness in responding to this issue. I understand the issue and will add some unit tests exercising the issue, and use your code as a basis for the fix.
