### ISSUE TITLE
Parsing a continous string

### ISSUE THREAD

**Issue by Igorp45** [r1chardj0n3s/parse#63]
I was trying to parse continous string having letters and numbers by the easiest way:

>>> parse('{:>w}{:g}{:w}{:g}{:w}', ' G3.80XA5.2M')
<Result ('G', 3.8, 'XA', 5.2, 'M') {}>
>>> parse('{:>w}{:g}{:w}{:g}{:w}', ' G3.80XA4.2M')
<Result ('G', 3.8, 'XA', 4.2, 'M') {}>

as far so good, but 

>>> parse('{:>w}{:g}{:w}{:g}{:w}', ' G3.80XA04.2M')
<Result ('G', 3.8, 'XA0', 4.2, 'M') {}>
>>> parse('{:>w}{:g}{:w}{:g}{:w}', ' G3.80XA44.2M')
<Result ('G', 3.8, 'XA4', 4.2, 'M') {}>
>>> parse('{:>w}{:g}{:w}{:g}{:w}', ' G3.80XA40M')
<Result ('G', 3.8, 'XA4', 0.0, 'M') {}>

changing input string a little bit I was getting bad results. 

I am missing something?

Igor

**Comment by r1chardj0n3s** [comment]
The "w" is matching numbers as well as letters. That's probably not what you want :/

Honestly it didn't occur to me that we don't have a *just letters* specifier in the syntax!

**Comment by Itshardtopickanusername** [comment]
just letters would be good, but would the 'not digits' {:D} specifier do the job?
