### ISSUE TITLE
Request: Add a copy of the license in a separate file

### ISSUE THREAD

**Issue by techalchemy** [r1chardj0n3s/parse#64]
Hey, we are vendoring this library over in https://github.com/pypa/pipenv and we are automating our vendoring process.  As part of the broader distribution process we are trying to handle our current licensing issues by including explicit license files for each of our vendored dependencies.  Would you be receptive to adding an additional LICENSE file with the text of the license of your software (MIT license I believe?)

If so I don't mind tossing a PR in this direction

**Comment by toddrme2178** [comment]
I am trying to package parse for openSUSE. We also need a LICENSE file.  Further, including a license file is one of the requirements of the MIT license.
