### ISSUE TITLE
Supported versions problem: python2.6, python2.5 (minor problem)

### ISSUE THREAD

**Issue by jenisys** [r1chardj0n3s/parse#66]
The "setup.py" file currently still states that python2.5 and python2.6 are supported. 
This may be true, but can currently not be proven because the test suite contains at least tests that run only on python2.7 and newer.

EXAMPLE:
```shell
$ pytest
platform ... -- Python 2.6.9, pytest-3.2.5, ...
...
self = <test_parse.TestParseType testMethod=test_decimal_value>
    def test_decimal_value(self):
        value = Decimal('5.5')
>       str_ = 'test {}'.format(value)
E       ValueError: zero length field name in format
```
NOTE: string-format without index or named args work only for Python2.7.x or newer AFAIK.

POSSIBLE SOLUTIONS:
* Drop support for older python versions
* Ensure that tests pass on all supported python version (and fix the test)

**Comment by r1chardj0n3s** [comment]
Thanks for pointing that out, those versions are definitely not supported.
