### ISSUE TITLE
Can I parse a JSON string with any dotted names?

### ISSUE THREAD

**Issue by tar-xzvff** [r1chardj0n3s/parse#70]
I want to parse JSON string.
But I got an error and I can not parse.

```
from parse import *

pattern = '{"name": {data.name}, "age": {data.age}}'
print(parse(pattern, '{"name": "test", "age": 25}'))
```

result
```
ValueError: format spec 'name":' not recognised
```

Is it impossible to parse a JSON character string with any dotted names?

**Comment by Itshardtopickanusername** [comment]
It seems like the brackets are the issue, I tried with square brackets and get the same error

**Comment by r1chardj0n3s** [comment]
I am confused as to why you wouldn't use `json.loads()` to parse JSON :-)
