### ISSUE TITLE
Getting UnicodeEncodeError during installation

### ISSUE THREAD

**Issue by sylviayap** [r1chardj0n3s/parse#76]
We are installing the parse as the dependency of the behave
And this is the traceback that we getting during the installation.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-install-sme0se0x/parse/setup.py", line 10, in <module>
    f.write(__doc__)
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 13017: ordinal not in range(128)
```

**Comment by r1chardj0n3s** [comment]
I can't reproduce this behavior under Python 2.7 or 3.6. Which Python version is being used to install behave? What versions of behave and parse are being installed?

**Comment by sylviayap** [comment]
Python 3.6
Behave 1.2.6

**Comment by r1chardj0n3s** [comment]
Hmm. Could I get more output from the command please? I just implemented a simple test like so:

    [testenv:behave]
    basepython = python3.6
    deps = behave
    commands = behave

and it produced this output:

```$ tox -e behave
GLOB sdist-make: /Users/richard/src/parse/setup.py
behave inst-nodeps: /Users/richard/src/parse/.tox/dist/parse-1.11.0.zip
behave installed: behave==1.2.6,parse==1.11.0,parse-type==0.4.2,six==1.12.0
behave runtests: PYTHONHASHSEED='3533099491'
behave runtests: commands[0] | behave
Feature: Showing off behave # features/stuff.feature:1

  Scenario: Run a simple test          # features/stuff.feature:3
    Given we have behave installed     # features/steps/example_steps.py:4 0.000s
    When we implement 5 tests          # features/steps/example_steps.py:8 0.001s
    Then behave will test them for us! # features/steps/example_steps.py:13 0.000s

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
3 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.002s
________________________________________________________ summary ________________________________________________________
  behave: commands succeeded
  congratulations :)
```

**Comment by r1chardj0n3s** [comment]
Could you please run the following in your environment and let me know the output?

    python3.6 -c 'import sys; print(sys.getdefaultencoding())'

**Comment by r1chardj0n3s** [comment]
Well, I am very confused. I've reverted the use of the unicode char in the docstring and released 1.11.1

**Comment by pvmilk** [comment]
Same issue when install in docker

```
FROM ubuntu:16.04
...
RUN pip --no-cache-dir install git+https://github.com/r1chardj0n3s/parse.git@COMMIT_NUMBER`
```

Any commit after @59fd257eb152a6fb215a09c15f2b4c6533a54c9c got the error.

**Comment by r1chardj0n3s** [comment]
@pvmilk my apologies, somehow I didn't push up the fix to github, which is done now.
