### ISSUE TITLE
LICENSE file in pypi tarball

### ISSUE THREAD

**Issue by pgajdos** [r1chardj0n3s/parse#82]
I know it may sound tiresome after two issues filled because of license already. Could you please still consider to add LICENSE file also in pypi tarball?

**Comment by kyluca** [comment]
I believe this PR should be sufficient to get the LICENSE file into the source dist https://github.com/kyluca/parse/pull/1

**Comment by pgajdos** [comment]
Thanks!

**Comment by kyluca** [comment]
Helps if I set the right upstream target for my PR! ahaha
https://github.com/r1chardj0n3s/parse/pull/89
