### ISSUE TITLE
Substring of radix digits

### ISSUE THREAD

**Issue by cup** [r1chardj0n3s/parse#84]
Python can convert from string to number:

~~~
>>> int('023')
23
~~~

but it can only handle radix digits:

~~~
>>> int('23G')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '23G'
~~~

Parse can convert from string to number:

~~~
>>> print(parse.parse('{:d}', '023'))
<Result (23,) {}>
~~~

but it can only handle radix digits:

~~~
>>> print(parse.parse('{:d}', '23G'))
None
~~~

Note that other languages handle this fine. For example C:

~~~c
#include <stdio.h>
#include <stdlib.h>
int main() {
   printf("%ld\n", strtol("23G", 0, 10));
}
~~~

> First, they decompose the input string into three parts:
> 1. An initial, possibly empty, sequence of white-space characters (as
> specified by **isspace()**)
> 2. A subject sequence interpreted as an integer represented in some radix
> determined by the value of **base**
> 3. A final string of one or more unrecognized characters, including the
> terminating NUL character of the input string.
> Then they shall attempt to convert the subject sequence to an integer, and
> return the result.

http://pubs.opengroup.org/onlinepubs/9699919799/functions/strtol.html

and JavaScript:

~~~js
parseInt('23G');
~~~

> If **S** contains a code unit that is not a radix-**R** digit, let **Z** be
> the substring of **S** consisting of all code units before the first such code
> unit; otherwise, let **Z** be **S**.

- https://developer.mozilla.org/Web/JavaScript/Reference/Global_Objects/Number/parseInt
- https://tc39.github.io/ecma262#sec-parseint-string-radix

and Ruby:

~~~rb
'23G'.to_i
~~~

http://ruby-doc.org/core/String.html#method-i-to_i

and Awk:

~~~awk
+"23G"
~~~

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html

**Comment by cup** [comment]
Here is a workaround:

~~~py
import re
int(re.search('^\d+', '23G')[0])
~~~

https://docs.python.org/library/re#re.search

**Comment by r1chardj0n3s** [comment]
parse() consumes the entire string, by design. I think you want to be using search():
```
>>> import parse
>>> parse.parse('{:d}', '23G')
>>> parse.search('{:d}', '23G')
<Result (23,) {}>
```
