### ISSUE TITLE
Iterate over results

### ISSUE THREAD

**Issue by jacobtomlinson** [r1chardj0n3s/parse#85]
It's not possible to iterate over results. It would be great if we could add this. 

As a workaround for now I've gone for
```
for group, value in result.named.items()
```

However it would be great if we could do 
```
for group, value in result.items()
```

**Comment by r1chardj0n3s** [comment]
What does this return if you've matched both positional and named items?

**Comment by jacobtomlinson** [comment]
I wasn't aware you could mix and match named and positional?

**Comment by r1chardj0n3s** [comment]
Ah! Indeed both `format()` and `parse()` support mixing named and positional values.

**Comment by wimglenn** [comment]
The "fixed" results are already iterable as a side-effect of `parse.Result` being indexable (i.e. implementing `__getitem__`). I don't think any Pythonic API is possible to combine the tuple of `result.fixed` with the dict of `result.named` in a single iterator.
