### ISSUE TITLE
parse with hyphen inside the Bracket format cant be recognized 

### ISSUE THREAD

**Issue by shiywang** [r1chardj0n3s/parse#86]
```
rp = parse.parse("RHEL-{rhel-version}-OSE-{ose-version}", pv)
rb = parse.parse("rhaos-{ose-version}-rhel-{rhel-version}", branch)

rp['rhel-version']  == None
```
but when I change to
```
rp = parse.parse("RHEL-{rhel}-OSE-{ose}", pv)
rb = parse.parse("rhaos-{ose}-rhel-{rhel}", branch)
```

it works

**Comment by r1chardj0n3s** [comment]
Looks like the allowed chars list for names needs to be expanded, perhaps to allow everything *except* the colon or closing brace char.

**Comment by codeasashu** [comment]
@r1chardj0n3s Any update? This is causing https://github.com/python-openapi/openapi-core/issues/672

**Comment by codeasashu** [comment]
OMG, thank you for quick solution :)
